# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

# Import the low-level C/C++ module

if __package__ or "." in __name__:
    from . import _pysw
else:
    import _pysw

import builtins as __builtin__
from functools import lru_cache

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def swe_julday(year, month, day, hour, gregflag):
    return _pysw.swe_julday(year, month, day, hour, gregflag)

def swe_sidtime(tjd):
    return _pysw.swe_sidtime(tjd)

def swe_revjul(tjd, gregflag):
    return _pysw.swe_revjul(tjd, gregflag)

def swe_calc(tjd, ipl, iflag):
    return _pysw.swe_calc(tjd, ipl, iflag)

def swe_calc_ut(tjd, ipl, iflag):
    return _pysw.swe_calc_ut(tjd, ipl, iflag)

def swe_fixstar_ut(star, tjd, iflag):
    return _pysw.swe_fixstar_ut(star, tjd, iflag)

def swe_houses(tjd_ut, geolat, geolon, hsys):
    return _pysw.swe_houses(tjd_ut, geolat, geolon, hsys)

def swe_houses_armc(armc, geolat, eps, hsys):
    return _pysw.swe_houses_armc(armc, geolat, eps, hsys)

def swe_close():
    return _pysw.swe_close()

def swe_deltat(tjd):
    return _pysw.swe_deltat(tjd)

def swe_set_ephe_path(path):
    return _pysw.swe_set_ephe_path(path)

def julday(y,m,d,h):
    if (y * 10000 + m * 100 + d) < 15821015:
        gregflag = 0
    else:
        gregflag = 1
    r = _pysw.swe_julday(y,m,d,h,gregflag)
    return r

def revjul(jd,gregflag=1):
    return _pysw.swe_revjul(jd,gregflag)

# Bounded caches prevent unbounded growth in long-running API processes.
_CALC_CACHE_MAXSIZE = 16384


@lru_cache(maxsize=_CALC_CACHE_MAXSIZE)
def _calc_cached(jd, pl, epheflag):
    r = _pysw.swe_calc(jd + delta(jd), pl, epheflag)
    return (r[0], r[1][0], r[-1])


@lru_cache(maxsize=_CALC_CACHE_MAXSIZE)
def _calc_ut_cached(jd, pl, epheflag):
    r = _pysw.swe_calc(jd, pl, epheflag)
    return (r[0], r[1][0], r[-1])


@lru_cache(maxsize=_CALC_CACHE_MAXSIZE)
def _calc_ut_with_speed_cached(jd, pl, epheflag):
    r = _pysw.swe_calc(jd, pl, epheflag | 256)
    return (r[0], r[1][0], r[1][3], r[-1])


def clear_calc_cache():
    _calc_cached.cache_clear()
    _calc_ut_cached.cache_clear()
    _calc_ut_with_speed_cached.cache_clear()

def calc(jd,pl,epheflag=4):
    return _calc_cached(jd, pl, epheflag)

def calc_ut(jd,pl,epheflag=4): 
    return _calc_ut_cached(jd, pl, epheflag)

def calc_ut_with_speed(jd,pl,epheflag=4): 
    return _calc_ut_with_speed_cached(jd, pl, epheflag)

def fixstar(star,jd,epheflag=4):
    r = _pysw.swe_fixstar_ut(star,jd,epheflag)
    return r 

def houses(jd,glt,glg):
    s,h = _pysw.swe_houses(jd,glt,glg,ord('K'))
    if s < 0 and glt < 66.53333336:
        print("error computing houses")
        return None
    return h

def local_houses(jd,glg,glt,epheflag):
    armc = glg
    if armc < 0:
        armc += 360 
    s,eps,e = calc(jd,-1,epheflag)
    s,h = _pysw.swe_houses_armc(armc,glt,eps,ord('K'))
    if s < 0:
        print("error computing local houses")
        return None
    return h

def delta(jd):
    return _pysw.swe_deltat(jd)

def planets(jd,epheflag,p=12):
    pl = []
    for i in range(p):
        if i == 10:
            continue
        s,l,e = calc(jd,i,epheflag)
        if s < 0:
            print("error: %s" % e)
            return None
        pl.append(l)
    return pl

setpath = _pysw.swe_set_ephe_path
sidtime = _pysw.swe_sidtime



