"""add user_interpretations and messages

Revision ID: fc9d99663118
Revises: 0001
Create Date: 2026-04-30 19:48:17.328476

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9d99663118'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interpretations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_persons_id', sa.Integer(), nullable=True),
    sa.Column('context_type', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('interp_year', sa.Integer(), nullable=True),
    sa.Column('interp_month', sa.Integer(), nullable=True),
    sa.Column('interp_day', sa.Integer(), nullable=True),
    sa.Column('interp_hour', sa.Integer(), nullable=True),
    sa.Column('interp_minute', sa.Integer(), nullable=True),
    sa.Column('location_country', sa.Text(), nullable=True),
    sa.Column('location_region', sa.Text(), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_longitude', sa.Float(), nullable=True),
    sa.Column('location_latitude', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_persons_id'], ['user_persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_interpretations_created', 'user_interpretations', ['created'], unique=False)
    op.create_index('ix_user_interpretations_user_id', 'user_interpretations', ['user_id'], unique=False)
    op.create_index('ix_user_interpretations_user_persons_id', 'user_interpretations', ['user_persons_id'], unique=False)
    op.create_table('user_interpretation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interpretation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interpretation_id'], ['user_interpretations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_uim_interpretation_id', 'user_interpretation_messages', ['interpretation_id'], unique=False)
    op.create_index('ix_uim_interpretation_position', 'user_interpretation_messages', ['interpretation_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uim_interpretation_position', table_name='user_interpretation_messages')
    op.drop_index('ix_uim_interpretation_id', table_name='user_interpretation_messages')
    op.drop_table('user_interpretation_messages')
    op.drop_index('ix_user_interpretations_user_persons_id', table_name='user_interpretations')
    op.drop_index('ix_user_interpretations_user_id', table_name='user_interpretations')
    op.drop_index('ix_user_interpretations_created', table_name='user_interpretations')
    op.drop_table('user_interpretations')
    # ### end Alembic commands ###
